server:
  servlet:
    context-path: /myshop

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  thymeleaf:
    cache: false

files:
  storepath:
    icons:  "C:\\myshop\\icons"
    images: "C:\\myshop\\images"
