server:
  servlet:
    context-path: /myshop


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  thymeleaf:
    cache: false

files:
  storepath:
    icons:  "C:\\myshop\\icons"
    images: "C:\\myshop\\images"

supershop:
  rabbitmq:
    exchange:   super-shop.exchange
    routingkey: super.shop
    queue:      super-shop.queue